CI: update v1.17 runner
Signed-off-by: Mahesh Karre <mahesh@edgeble.ai>

diff --git a/.github/workflows/kernel-build.yml b/.github/workflows/kernel-build.yml
--- a/.github/workflows/kernel-build.yml
+++ b/.github/workflows/kernel-build.yml
@@ -15,6 +15,27 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v1
 
+      - name: Setup SSH
+        env:
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
+          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
+        run: |
+          mkdir -p ~/.ssh/
+          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
+          echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
+          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
+          chmod 600 ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa.pub
+          chmod 600 ~/.ssh/known_hosts
+
+          # Configure SSH to use this key for GitLab
+          echo -e "Host gitlab.com\n\tIdentityFile ~/.ssh/id_rsa\n" >> ~/.ssh/config
+
+          # Test the SSH connection (optional)
+          ssh -T git@gitlab.com || echo "SSH connection test failed, but continuing..."
+
+
       - name: Clone and Compile
         run: |
           git clone git@gitlab.com:edgeble/core/kernel-6.1.git && cd kernel-6.1
